#!/bin/bash -e
IMAGE_NAME=mega-drive-megawifi
docker build -t $IMAGE_NAME .
docker run \
    -e VERSION \
    -e CMOCKA_MESSAGE_OUTPUT \
    -e CMOCKA_XML_FILE \
    --rm \
    -v $(pwd):/app \
    -w /app \
    -it \
    $IMAGE_NAME \
    "$@"
